---
- name: "adding new publickeys to the authorized keys of all the hosts"
  hosts: all
  become_user: root
  gather_facts: true
  tasks:
  
  - name: "adding new public keys and removing all other privious keys"
    authorized_key:
      user: root
      key: "{{ lookup('file', '/root/.ssh/id_rsa1.pub') }}"
      state: present
      exclusive: True

