version: '2'
services: 
  wordpress:
    image: wordpress
    ports: 
      - "8000:80"
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db:3306 
      WORDPRESS_DB_PASSWORD: redhat08
    volumes:
      - WORDPRESS_DATA:/var/lib/wordpress
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - MYSQL_DATA:/var/lib/mysql
    restart: always
    env_file:
      - evs.env
volumes:
  WORDPRESS_DATA: {} 
  MYSQL_DATA: {}
