---
- name: "Healthcheck and Deployement"
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
   - name: "copying war into tomcat webapps folder"
     command: cp /home/vagrant/Spring3HibernateApp.war /var/lib/tomcat8/webapps/
          
   - name: "restarting server"
     service:
       name: tomcat8
       state: restarted

   - name: "wait for website to come up"
     uri:
       url: "http://192.168.33.50:8080/Spring3HibernateApp"
       status_code: 200
     register: result
     until: result.status == 200
     retries: 5
     delay: 10


